// <auto-generated />
namespace Fulcrum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ParameterizedQueryReference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParameterizedQueryReference));
        
        string IMigrationMetadata.Id
        {
            get { return "201512090957420_ParameterizedQueryReference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
