// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FulcrumSeed.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BasicProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasicProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201511012022210_BasicProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
